default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: loldev

test:
  <<: *default
  database: loltest

production:
  url: <%= ENV['DATABASE_URL'] %>
